#!/bin/bash
set -euo pipefail
cd /data/serverfiles
export LD_LIBRARY_PATH=/data/serverfiles:/data/serverfiles/valve/dlls
exec /usr/local/lib/gamepanel/source-console ./hltv -console -ip 0.0.0.0 -port "$SERVER_PORT"
