import React from 'react';
import { createRoot } from 'react-dom/client';
import { HostNetwork } from '../components/HostNetwork';
import { ThemeProvider } from '../contexts/ThemeContext';
import '@ovhcloud/ods-react/normalize-css';
import '@ovhcloud/ods-themes/default/css';
import '@ovhcloud/ods-themes/default/fonts';
import '../src/ui/theme/ods-dark.css';
import '../src/ui/theme/ods-light.css';
import '../styles/globals.css';
const onDirtyChange = () => {};
createRoot(document.getElementById('root')!).render(<ThemeProvider><main className="p-5 text-slate-900 dark:text-slate-100" style={{ maxWidth: 1200, margin: 'auto' }}><HostNetwork nodeId="local" onDirtyChange={onDirtyChange} /></main></ThemeProvider>);
