import React from 'react';
import { createRoot } from 'react-dom/client';
import { ScheduledTasksTab } from '../components/serverSettings/ScheduledTasksTab';
import { ThemeProvider } from '../contexts/ThemeContext';
import '@ovhcloud/ods-react/normalize-css';
import '@ovhcloud/ods-themes/default/css';
import '../src/ui/theme/ods-dark.css';
import '../src/ui/theme/ods-light.css';
import '../styles/globals.css';
createRoot(document.getElementById('root')!).render(<ThemeProvider><main style={{padding:16}}><ScheduledTasksTab serverId={8} serverProvider="external" serverBackupSupported canRead canWrite administrator={!location.search.includes('gameAdmin')} permissions={['server.power', 'backups.create', 'server.command.send']} contentBg="" borderColor="" textPrimary="" textSecondary="" hoverBg="" inputBg="" inputBorder="" /></main></ThemeProvider>);
