import React from 'react';
import { createRoot } from 'react-dom/client';
import { NodeNetwork } from '../components/NodeNetwork';
import { ThemeProvider } from '../contexts/ThemeContext';
import '@ovhcloud/ods-react/normalize-css';
import '@ovhcloud/ods-themes/default/css';
import '@ovhcloud/ods-themes/default/fonts';
import '../src/ui/theme/ods-dark.css';
import '../src/ui/theme/ods-light.css';
import '../styles/globals.css';
const dirty = () => {};
createRoot(document.getElementById('root')!).render(<ThemeProvider><main className="p-5 text-slate-900 dark:text-slate-100" style={{ maxWidth: 1400, margin: 'auto' }}><NodeNetwork nodeId="local" nodeName="WAW2" onDirtyChange={dirty} /></main></ThemeProvider>);
