import React from 'react';
import { createRoot } from 'react-dom/client';
import { SftpAccessCard } from '../components/serverSettings/SftpAccessCard';
import { ThemeProvider } from '../contexts/ThemeContext';
import '@ovhcloud/ods-react/normalize-css';
import '@ovhcloud/ods-themes/default/css';
import '../src/ui/theme/ods-dark.css';
import '../src/ui/theme/ods-light.css';
import '../styles/globals.css';
import '../components/serverSettings/container-settings.css';
createRoot(document.getElementById('root')!).render(<ThemeProvider><main style={{ padding: 20, maxWidth: 1100, margin: 'auto' }}><SftpAccessCard serverId={8} canManage={!location.search.includes('readonly')} /></main></ThemeProvider>);
