import { useEffect, useState } from 'react';
import { LockKeyhole, Plus } from 'lucide-react';
import { AppSelect } from '../src/ui/components/AppSelect';
import { nodesRequest, type ExecutionNode } from '../utils/nodesApi';
import type { GameTemplate } from '../utils/gameTemplates';

export function TemplateSharedMount({mounts,onChange}:{mounts:GameTemplate['mounts'];onChange:(mounts:GameTemplate['mounts'])=>void}) {
  const [nodes,setNodes] = useState<ExecutionNode[]>([]), [node,setNode] = useState('');
  const [packages,setPackages] = useState<{id:string;name:string;version:string;sha256:string}[]>([]), [selected,setSelected] = useState('');
  const [folder,setFolder] = useState('.'), [destination,setDestination] = useState('/data/serverfiles/shared'), [error,setError] = useState('');
  useEffect(()=>{let active=true;nodesRequest<{nodes:ExecutionNode[]}>('/api/nodes').then(r=>{if(active){const enabled=r.nodes.filter(n=>n.enabled);setNodes(enabled);setNode(enabled[0]?.id || 'local');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
  useEffect(()=>{if(!node)return;let active=true;setPackages([]);setSelected('');setError('');const url=(node==='local'?'':`/api/nodes/${node}/runtime`)+'/api/system/shared-files';nodesRequest<{packages:typeof packages}>(url).then(r=>{if(active){setPackages(r.packages);setSelected(r.packages[0]?.id||'');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[node]);
  const input='mt-1 w-full rounded-xl border border-slate-300 bg-transparent px-3 py-2 text-sm dark:border-slate-600';
  return <details className="rounded-xl border border-slate-300 p-4 dark:border-slate-700"><summary className="cursor-pointer font-medium">Add shared folder</summary><div className="mt-4 space-y-4"><div className="grid gap-4 md:grid-cols-2"><div><span className="mb-1 block text-sm">Package node</span><AppSelect controlLabel="Package node" value={node} onChange={setNode} options={[{value:'local',label:'Local'},...nodes.map(n=>({value:n.id,label:n.name}))]}/></div><div><span className="mb-1 block text-sm">Shared package</span><AppSelect controlLabel="Shared package" value={selected} onChange={setSelected} options={packages.map(p=>({value:p.id,label:`${p.name} · ${p.version}`}))}/></div><label className="text-sm">Folder in package<input className={input} value={folder} onChange={e=>setFolder(e.target.value)}/></label><label className="text-sm">Mount destination<input className={input} value={destination} onChange={e=>setDestination(e.target.value)}/></label></div>{error && <p role="alert" className="text-sm text-red-500">{error}</p>}<div className="flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-xs text-cyan-500"><LockKeyhole size={14}/>Read only</span><button type="button" disabled={!selected || !folder || !destination} className="inline-flex items-center gap-2 rounded-xl bg-blue-700 px-4 py-2 text-sm text-white disabled:opacity-40" onClick={()=>{const pkg=packages.find(p=>p.id===selected);if(!pkg)return;let n=mounts.length;while(mounts.some(m=>m.key===`shared_${n}`))n++;onChange([...mounts,{key:`shared_${n}`,containerPath:destination,shared:{package:pkg.id,sha256:pkg.sha256,path:folder}}]);}}><Plus size={16}/>Add folder</button></div></div></details>;
}
